### ISSUE TITLE
sprite helper doesn't seem to respect a base uri.

### ISSUE THREAD

**Issue by brentkirby** [Compass/compass-rails#34]
We're using a rails app under a base uri (using Rails/RackBaseURI with passenger).  Images using the image-url helper generate the proper paths/urls when compiled, but sprite helpers seem to always use /assets (thereby throwing a 404). I tried setting a few config options in application.rb to see if that would work

``` ruby

config.compass.images_dir = "/app/assets/images"
config.compass.generated_images_dir = "/app/assets/images"
config.compass.http_generated_images_path = "/our-sub-uri/assets"

```

but urls generated by sprites still use /assets. The first 2 configuration options we ended up having to specify with the 3rd, or else compass would error saying it could not find our sprite paths.  We are using `sprite-map` and `sprite` as so.

``` scss
$fields:sprite-map("forms/*.png", $position: 0%, $spacing: 15px, $repeat: no-repeat);

#selector{ background:sprite($fields, arrow); }
```

Everything works perfectly until deployed under the sub-uri. Is there a configuation setting I'm missing somewhere?
