### ISSUE TITLE
Sprite path becomes /all-s97e8fd834b.png instead of /assets/all-s97e8fd834b.png

### ISSUE THREAD

**Issue by Sephi-Chan** [Compass/compass-rails#99]
After the generated sprite image changed automatically (when I added an image to the watched folder), I noticed that the path in the stylesheet suddenly became wrong:

``` css
.all-sprite, .all-header, .all-small-header, .header-container .title-container.main h1 {
  background: url(/all-s97e8fd834b.png) no-repeat;
}
```

Juste before the sprite regeneration, the path was perfectly right!

I use Rails 4.0.0 with the master of Compass (aea69635f6000bbc7180f7fdd0ce216f904db30d at the moment).

To work around it, I ran `rake tmp:clear` and restarted the server.
